apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeletclient-pod
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeletclient-pod
rules:
- apiGroups: [""]
  resources:
  - nodes/log
  - nodes/metrics
  - nodes/proxy
  - nodes/spec
  - nodes/stats
  verbs:
  - get
- apiGroups: [""]
  resources:
  - nodes
  verbs:
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeletclient-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeletclient-pod
subjects:
- kind: ServiceAccount
  name: kubeletclient-pod
  namespace: kube-system
---
apiVersion: v1
kind: Pod
metadata:
  name: kubeletclient-pod
  namespace: kube-system
spec:
  tolerations:
  - operator: "Exists"
  serviceAccountName: kubeletclient-pod
  restartPolicy: Never
  containers:
  - name: alpine
    image: localhost:5000/alpine:latest
    command: ["sleep", "infinity"]
